-- Nuevos jerseys: Santos Laguna (Oribe Peralta, Chucho Benítez), Querétaro (2016/2017),
-- Juventus 3ra equipación 2023, Real Madrid Sergio Ramos 2014, Arsenal Henry 2003,
-- Inglaterra Kane 2018 y Alemania 2012

insert into jerseys
  (nombre, club, pais, bandera, liga, marca, talla, anio, precio, color, imagen, imagen_espalda, descripcion, disponible, cantidad)
values
  (
    'Santos Laguna Visitante 2014 - Oribe Peralta',
    'Club Santos Laguna',
    'México',
    '🇲🇽',
    'Liga MX',
    'Puma',
    'L',
    2014,
    800,
    'Negro',
    'Jerseys/Norte america/Liga MX/Santos/Santos4.png',
    'Jerseys/Norte america/Liga MX/Santos/Santos5.png',
    'Jersey oficial visitante del Santos Laguna temporada 2014, en negro y gris de manga larga, marca Puma, personalizado con el número 24 de Oribe Peralta.',
    true,
    1
  ),
  (
    'Santos Laguna Local 2011 - Chucho Benítez #11',
    'Club Santos Laguna',
    'México',
    '🇲🇽',
    'Liga MX',
    'Puma',
    'M',
    2011,
    800,
    'Verde y Blanco',
    'Jerseys/Norte america/Liga MX/Santos/Santos2.png',
    'Jerseys/Norte america/Liga MX/Santos/Santos3.png',
    'Jersey oficial local del Santos Laguna temporada 2011, en las clásicas franjas verde y blanco, marca Puma, personalizado con el nombre y número de Chucho Benítez #11.',
    true,
    1
  ),
  (
    'Querétaro Visitante 2016',
    'Querétaro FC',
    'México',
    '🇲🇽',
    'Liga MX',
    'Puma',
    'S',
    2016,
    700,
    'Blanco',
    'Jerseys/Norte america/Liga MX/Queretaro/Queretar1.png',
    null,
    'Jersey oficial visitante del Querétaro FC temporada 2016, en blanco plateado con detalles en azul claro, marca Puma.',
    true,
    1
  ),
  (
    'Querétaro Local 2017',
    'Querétaro FC',
    'México',
    '🇲🇽',
    'Liga MX',
    'Puma',
    'S',
    2017,
    700,
    'Azul y Negro',
    'Jerseys/Norte america/Liga MX/Queretaro/Queretaro2.png',
    null,
    'Jersey oficial local del Querétaro FC temporada 2017, en azul y negro, marca Puma, patrocinio Imagen Televisión y Banco Multiva.',
    true,
    1
  ),
  (
    'Juventus 3ra Equipación 2023',
    'Juventus FC',
    'Italia',
    '🇮🇹',
    'Serie A',
    'Adidas',
    'XL',
    2023,
    1000,
    'Negro',
    'Jerseys/Europa/Serie A/Juventus/JV4.png',
    null,
    'Jersey oficial de tercera equipación de la Juventus temporada 2023-24, en negro con patrocinio Jeep, marca Adidas.',
    true,
    1
  ),
  (
    'Arsenal Local 2003 - Henry #14',
    'Arsenal FC',
    'Inglaterra',
    '🏴',
    'Premier League',
    'Nike',
    'XL',
    2003,
    2500,
    'Rojo y Blanco',
    'Jerseys/Europa/Premier League/Arsenal/Arsenal2.png',
    'Jerseys/Europa/Premier League/Arsenal/Arsenal3.png',
    'Jersey oficial local del Arsenal FC temporada 2003-04 (Invencibles), en rojo con mangas blancas, patrocinio O2, marca Nike, personalizado con el nombre y número de Henry #14.',
    true,
    1
  ),
  (
    'Inglaterra Local 2018 - Kane #9',
    'Selección de Inglaterra',
    'Inglaterra',
    '🏴',
    'Selección Nacional',
    'Nike',
    'S',
    2018,
    1100,
    'Blanco',
    'Jerseys/Internacional/Inglaterra/Inglaterra.png',
    'Jerseys/Internacional/Inglaterra/Inglaterra2.png',
    'Jersey oficial local de la selección de Inglaterra para el Mundial de Rusia 2018, en blanco hueso, marca Nike, personalizado con el nombre y número de Kane #9.',
    true,
    1
  ),
  (
    'Real Madrid Local 2014 - Sergio Ramos #4',
    'Real Madrid CF',
    'España',
    '🇪🇸',
    'La Liga',
    'Adidas',
    'S',
    2014,
    1700,
    'Blanco',
    'Jerseys/Europa/La liga/Real madrid/RM11.png',
    'Jerseys/Europa/La liga/Real madrid/RM12.png',
    'Jersey oficial local del Real Madrid temporada 2013-14, blanco con detalles naranjas y patrocinio Fly Emirates, personalizado con el nombre y número de Sergio Ramos #4.',
    true,
    1
  ),
  (
    'Alemania Visitante 2012',
    'Selección de Alemania',
    'Alemania',
    '🇩🇪',
    'Selección Nacional',
    'Adidas',
    'XL',
    2012,
    1500,
    'Verde',
    'Jerseys/Internacional/Alemania/Alemania.png',
    null,
    'Jersey oficial visitante de la selección de Alemania para la Eurocopa 2012, en verde con detalles blancos, marca Adidas, edición conmemorativa 1972-2012.',
    true,
    1
  );
